### ISSUE TITLE
Alignment of Example: HTML in readme

### ISSUE THREAD

**Issue by pbhj** [sghall/resonance#23]
### Alignment of example is wrong

In "Example: HTML" of readme the alignment on FF Mobile is wrong pushing the column of tuples off to the right outside the visual box presented by the UI.

### Steps to reproduce (only needed for problems)
View on mobile. FWIW alignment is correct when viewed in landscape for me, only portrait mode is wrong.

### Versions (only needed for problems)

- Resonance: 
- React: 
- Browser:

**Comment by sghall** [comment]
Yeah.  I should make that demo a little nicer.  It's just using simple absolute positioning so it will spill outside the container.  I added it to show that you can animate HTML since  all the other demos are SVG stuff.  I'd like to have a few more HTML demos. PRs are welcome on this!

**Comment by pbhj** [comment]
https://ibb.co/jS3Xpa

**Comment by sghall** [comment]
Fixed this example.  Thanks!
