### ISSUE TITLE
Using webpackSunburst plot

### ISSUE THREAD

**Issue by tayabsoomro** [sghall/resonance#28]
Hi, 

I would like to use the webpackSunburst plot that is up in the example here: https://sghall.github.io/resonance/#/redux-examples/webpack-sunburst, but I can't seem to find a way to do that. I looked into the code and there are too many dependent files. With this library, is there like a simple import that I could use (ex: `import {Sunburst} from 'resonance'`) to have Sunburst readily available?

**Comment by sghall** [comment]
Hi there.  Those are just demos in this repo.  There is a sunburst done with [react-move](https://github.com/react-tools/react-move) (where this code moved to)  on Codesandbox https://codesandbox.io/s/v3x0yw11q5

More info in this issue https://github.com/react-tools/react-move/issues/31
